version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
        XDEBUG: '${XDEBUG}'
    image: sail-7.4/app
    container_name: solawir_php_app
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      PHP_IDE_CONFIG: "serverName=enableDebug"
    volumes:
      - '.:/var/www/html'
    networks:
      - backend-network
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8.0'
    container_name: '${DB_HOST}'
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  mysql-ut:
    image: 'mysql:8.0'
    container_name: '${DB_HOST}'
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_DATABASE: 'solawi_ut'
      MYSQL_USER: 'unit_test'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - dbdata-ut:/var/lib/mysql/
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-psecret" ]
      retries: 3
      timeout: 5s

networks:
  backend-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
  dbdata-ut:
    driver: local
