name: "CI"

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.3

    services:
      mysql:
        image: mysql:15.1
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: solawi_ut
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install composer dependencies
        run: |
          composer install --no-scripts
      - name: Prepare Laravel Application
        run: |
          php -r "file_exists('.env') || copy('.env.testing.example', '.env');"
          php artisan key:generate
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs: unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master
        env:
          REPOSRC: ${{ github.server_url }}/${{ github.repository }}.git
          LOCALREPO: ${{ secrets.LOCALREPO }}
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          envs: REPOSRC,LOCALREPO
          script: |
            if [ ! -d $LOCALREPO ]
            then
                git clone $REPOSRC $LOCALREPO
            else
                cd $LOCALREPO
                git checkout -f
                git pull
            fi
